<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Documentation</name>
   <tag></tag>
   <elementGuidId>4d085cd1-3331-4051-9b8a-c7a6f9fb8dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.breadcrumb-item.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Documentation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;breadcrumb&quot;i >> internal:role=link[name=&quot;Documentation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3965b874-2ac8-4d96-83e6-648d41c27e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.selenium.dev/documentation/</value>
      <webElementGuid>3984531c-09a8-40bc-ac5c-bbef9ba0ac59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>dabe0e66-e851-4348-a8c2-9759a407259f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;td-section&quot;]/div[@class=&quot;container-fluid td-outer&quot;]/div[@class=&quot;td-main&quot;]/div[@class=&quot;row flex-xl-nowrap&quot;]/main[@class=&quot;col-12 col-md-9 col-xl-8 ps-md-5&quot;]/nav[@class=&quot;td-breadcrumbs td-breadcrumbs__single&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item active&quot;]/a[1]</value>
      <webElementGuid>eb60030e-20a9-4406-9eb3-3491ed05d296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Documentation')]</value>
      <webElementGuid>9e6a3360-4e2a-46ed-83db-457be48f13c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print entire section'])[1]/following::a[1]</value>
      <webElementGuid>280ae975-f137-4564-ae22-5a7afe115586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create project issue'])[1]/following::a[2]</value>
      <webElementGuid>c92be7fe-dd6a-49c1-85c8-443369888185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v4.0'])[1]/preceding::a[1]</value>
      <webElementGuid>90ca9d22-4852-4ac8-b323-42cc9121feec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Selenium Browser Automation Project'])[1]/preceding::a[1]</value>
      <webElementGuid>b492eed4-5731-489c-a13d-f74ffb42c272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.selenium.dev/documentation/')])[2]</value>
      <webElementGuid>93577e3a-858b-4574-8cc6-e17cddec6ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>6448952d-eefd-497f-ad49-a0a92090f821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.selenium.dev/documentation/' and (text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>fad6c070-98ee-41e8-aa95-97d37700a36b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
