<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IE Driver Server</name>
   <tag></tag>
   <elementGuidId>3520b4b5-fbf3-46d4-9ed8-80f1060ac761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m-documentationie_driver_server</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='m-documentationie_driver_server']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#m-documentationie_driver_server</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29afa864-296a-4581-b396-ec9a1b67c4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/documentation/ie_driver_server/</value>
      <webElementGuid>1dc3aa8e-45bc-4a82-92ba-631b319fe9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-left ps-0 td-sidebar-link td-sidebar-link__section</value>
      <webElementGuid>930f1d8d-28a7-47a5-8412-0de8c19f8345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m-documentationie_driver_server</value>
      <webElementGuid>7e7b2a51-c568-4e03-a1d6-b13f8cd1bfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IE Driver Server</value>
      <webElementGuid>375da048-3a80-41d4-adfd-6e5219eca539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-documentationie_driver_server&quot;)</value>
      <webElementGuid>3e538a4d-7793-4366-ad9b-aabcf3fb8260</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='m-documentationie_driver_server']</value>
      <webElementGuid>e23fb6b3-2840-45c7-9ee8-541cc6336f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='m-documentationie_driver_server-li']/a</value>
      <webElementGuid>050ff9f3-c52e-48bb-b598-d4b6cc69432a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External datastore'])[1]/following::a[1]</value>
      <webElementGuid>550fed8c-b8ec-416f-8241-ab3a22a7d063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize Node'])[1]/following::a[2]</value>
      <webElementGuid>aacab4eb-e8f5-429b-8add-4407184c4ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Internals'])[1]/preceding::a[1]</value>
      <webElementGuid>cb682e77-fe92-415a-af0a-67e151006d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/documentation/ie_driver_server/')]</value>
      <webElementGuid>70d40d63-ec0b-4ccc-8c2e-10452643fc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[5]/a</value>
      <webElementGuid>e1ae31a8-a5e5-4261-8a3d-546d2d20acc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/documentation/ie_driver_server/' and @id = 'm-documentationie_driver_server' and (text() = 'IE Driver Server' or . = 'IE Driver Server')]</value>
      <webElementGuid>6eb0acbf-3a26-4610-9b11-ba56dbef4d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
