<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Legacy</name>
   <tag></tag>
   <elementGuidId>38a5578c-5267-489a-88cf-941c90452b0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m-documentationlegacy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='m-documentationlegacy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#m-documentationlegacy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>510d8bc1-5bd4-4bcd-9f96-526e29be8673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/documentation/legacy/</value>
      <webElementGuid>e10fd6f8-47d8-44f3-bd9a-84a805f55a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-left ps-0 td-sidebar-link td-sidebar-link__section</value>
      <webElementGuid>4a6d244f-1c12-4e5b-b4a7-ea479c9c0d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m-documentationlegacy</value>
      <webElementGuid>f29c86c9-45ac-43a3-b9d3-a31f11d56ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Legacy</value>
      <webElementGuid>8347c7bc-1581-44cd-ba83-362d67ac391e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-documentationlegacy&quot;)</value>
      <webElementGuid>128afb64-2199-400e-b990-9eba3e3f4ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='m-documentationlegacy']</value>
      <webElementGuid>5b93c6fb-14bd-41ba-8257-3c0079e87fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='m-documentationlegacy-li']/a</value>
      <webElementGuid>0fddd51b-26a5-47bd-9124-ba1549f5a03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two Factor Authentication'])[1]/following::a[1]</value>
      <webElementGuid>4cfc3c3c-ec9f-484c-b4e8-98300366ec24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link spidering'])[1]/following::a[2]</value>
      <webElementGuid>9c7be1b8-c70b-4c17-88d4-ad4c771eafc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium 1'])[1]/preceding::a[1]</value>
      <webElementGuid>cb1945c7-37f6-456f-afff-5f32a09274d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/documentation/legacy/')]</value>
      <webElementGuid>7f9a1206-af43-4271-8e4d-23fe4b6ae2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>23c12c90-cf3f-4f9c-8e9c-03d23cde151c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/documentation/legacy/' and @id = 'm-documentationlegacy' and (text() = 'Legacy' or . = 'Legacy')]</value>
      <webElementGuid>b193d596-51a5-4d33-84b3-77bd7f8ed873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
