<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WebDriver</name>
   <tag></tag>
   <elementGuidId>67e5ee70-bdc6-4598-b9f9-d7e1af1f44bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m-documentationwebdriver</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='m-documentationwebdriver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#m-documentationwebdriver</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b1b6087-298e-4f6a-b2aa-03ca8a0f783e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/documentation/webdriver/</value>
      <webElementGuid>c660c5c1-555c-4f8f-a054-202c4c1e863d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-left ps-0 td-sidebar-link td-sidebar-link__section</value>
      <webElementGuid>659f8105-4d84-4b8a-82c8-afc3a73041d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m-documentationwebdriver</value>
      <webElementGuid>7ee99d74-adb6-4938-83bf-cc44fd66b7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WebDriver</value>
      <webElementGuid>ef4b5f68-0afb-4438-9f6d-093de0fa346d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-documentationwebdriver&quot;)</value>
      <webElementGuid>9bb1e9a9-6481-4f38-baa7-073c8c5e63b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='m-documentationwebdriver']</value>
      <webElementGuid>cea0854b-c235-48b7-8acf-9cda81eba4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='m-documentationwebdriver-li']/a</value>
      <webElementGuid>705a5140-d004-4782-8bef-e48807d9adc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::a[1]</value>
      <webElementGuid>d1fcf572-eebc-46f3-9870-2d4464654274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Components'])[1]/following::a[2]</value>
      <webElementGuid>6594d315-8d39-424d-b923-6742a1c437da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getting Started'])[1]/preceding::a[1]</value>
      <webElementGuid>24fb6321-fb5f-4645-98c1-a12d8a360681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/documentation/webdriver/')]</value>
      <webElementGuid>ff20349b-e210-4a9e-a59f-834c306b3b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/a</value>
      <webElementGuid>c6cb3129-c39d-40ad-a292-45dc44e1a529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/documentation/webdriver/' and @id = 'm-documentationwebdriver' and (text() = 'WebDriver' or . = 'WebDriver')]</value>
      <webElementGuid>49670eb3-f1e4-40e8-8cd0-45f2ef71a89d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
