<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grid</name>
   <tag></tag>
   <elementGuidId>bcd74097-32a2-41d6-88f9-51ec664016a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m-documentationgrid > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='m-documentationgrid']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#m-documentationgrid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61e55a2d-2774-493b-8254-dc0706364046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grid</value>
      <webElementGuid>c57a7b6f-3d9e-4c23-99f2-82ff3e05e3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-documentationgrid&quot;)/span[1]</value>
      <webElementGuid>962bdc95-e95b-48e3-abed-38e1f2268846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='m-documentationgrid']/span</value>
      <webElementGuid>f6b65c09-1cba-419d-b4f0-0dbdc03ef816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Manager'])[1]/following::span[1]</value>
      <webElementGuid>9337fffc-2ec7-4499-9667-e1cc449271fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade to Selenium 4'])[1]/following::span[2]</value>
      <webElementGuid>0570a6d1-a2b5-4eb0-a1a8-7bf8272f4e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getting Started'])[2]/preceding::span[1]</value>
      <webElementGuid>77a15c50-c634-47e6-986d-44159076f293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When to Use Grid'])[1]/preceding::span[2]</value>
      <webElementGuid>a87ebd7d-bc9c-4c00-ae20-55d7d051e306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grid']/parent::*</value>
      <webElementGuid>db9cc534-6198-46a1-aa46-d9d8699fd5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/a/span</value>
      <webElementGuid>8a066dff-ba46-499f-8e8c-30ad934328f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Grid' or . = 'Grid')]</value>
      <webElementGuid>8fe42d70-9ead-48e1-81b3-6ba0d8ac3581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
