<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Legacy</name>
   <tag></tag>
   <elementGuidId>f39e4f6b-7032-4a21-857b-5a8802eba776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m-documentationlegacy > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='m-documentationlegacy']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#m-documentationlegacy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13890e01-164e-4ea5-9138-04c8b937515f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Legacy</value>
      <webElementGuid>cccf920c-cfd9-4625-8452-791fbb4e86e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m-documentationlegacy&quot;)/span[1]</value>
      <webElementGuid>f4537071-5fc1-4d31-b867-58e56cf58c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='m-documentationlegacy']/span</value>
      <webElementGuid>016651c9-1515-4a75-910f-10c88e69ecbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two Factor Authentication'])[1]/following::span[1]</value>
      <webElementGuid>03ba953e-d2e0-48e6-8ab8-b74462e16e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link spidering'])[1]/following::span[2]</value>
      <webElementGuid>eb6a3b96-4a56-459b-9481-56b582c61276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium 1'])[1]/preceding::span[1]</value>
      <webElementGuid>af99a261-75fa-45f4-95c4-136dea7fd893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium 2'])[1]/preceding::span[2]</value>
      <webElementGuid>b3b70c74-a615-4441-90e1-e91ed335293e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Legacy']/parent::*</value>
      <webElementGuid>1e42af54-b221-4ace-8ddd-9a68e62bd6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/span</value>
      <webElementGuid>4b5554fd-88bf-4ea8-a3e9-015646c530ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Legacy' or . = 'Legacy')]</value>
      <webElementGuid>ad97afc9-49ac-42b0-8c3a-a01ecf7059d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
