<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2</name>
   <tag></tag>
   <elementGuidId>6a11e795-7c68-4630-9d5e-e6f1e5e183a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[53]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;2, Sunday, March 2025. Available. Select as check-in date.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>922d4011-7539-4262-8e0b-c40396fb6201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ce6cb43-fe7c-4be4-b418-869a973be1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2, Sunday, March 2025. Available. Select as check-in date.</value>
      <webElementGuid>bf39fd7f-64f6-43b3-9ab1-8f3916766088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr</value>
      <webElementGuid>e1692853-fbf2-456c-a778-3d3f70ad37ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state--date-string</name>
      <type>Main</type>
      <value>2025-03-02</value>
      <webElementGuid>e4ab5d1d-7dac-4aad-bccc-f9535029eb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>38291a44-9353-44d5-b0a4-d730f4c517d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1aa91ea2-9478-4074-8492-b3321188afa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel--tabs--0&quot;)/div[@class=&quot;d1xjigzy atm_h_1h6ojuz__7pk1ck atm_9s_1txwivl__7pk1ck atm_ar_1bp4okc__7pk1ck atm_fc_1h6ojuz__7pk1ck dir dir-ltr&quot;]/div[@class=&quot;h1yby4o2 atm_9s_1o8liyq atm_mk_h2mmj6 h12enwjs atm_vy_1a0j60c atm_gz_vgba9w atm_h0_vgba9w dir dir-ltr&quot;]/div[4]/div[@class=&quot;e46z8ty atm_l0_15vqwwr atm_vy_1osqo2v dir dir-ltr&quot;]/div[@class=&quot;ecjc60a atm_9s_1txwivl atm_uq_1e032xh atm_uv_1ytfnp0 atm_h_v2br90 dir dir-ltr&quot;]/div[@class=&quot;m1uqgy7e atm_9s_11p5wf0 atm_dz_1u8mbql atm_n5_yh40bf atm_vy_1osqo2v atm_l8_1w78mzc atm_ks_zryt35 h1pfdthe atm_gz_d4y9na atm_h0_d4y9na dir dir-ltr&quot;]/button[@class=&quot;d11exu1w atm_vy_1osqo2v atm_1w_gbua2q atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_fb_1cl4t0h atm_c8_dlk8xv atm_cs_10d11i2 atm_7l_dezgoh atm_9j_tlke0l atm_vb_glywfm atm_70_glywfm atm_2d_n7od8j atm_3f_n7od8j atm_lb_n7od8j atm_lh_n7od8j atm_vy_1osqo2v_vmtskl atm_e2_1osqo2v_vmtskl atm_mk_stnw88_vmtskl atm_92_1yyfdc7_vmtskl atm_5j_1ssbidh_vmtskl atm_wq_1mrwo0b_vmtskl atm_3f_11x2w5_1rqz0hn_uv4tnr atm_kd_glywfm_1w3cfyq atm_3f_glywfm_e4a3ld atm_l8_idpfg4_e4a3ld atm_gi_idpfg4_e4a3ld atm_3f_glywfm_1r4qscq atm_kd_glywfm_6y7yyg atm_uc_aaiy6o_9xuho3 atm_70_1kppo7g_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_kd_glywfm_pfnrn2_1oszvuo atm_3f_glywfm_1icshfk_1oszvuo atm_l8_idpfg4_1icshfk_1oszvuo atm_gi_idpfg4_1icshfk_1oszvuo atm_3f_glywfm_b5gff8_1oszvuo atm_kd_glywfm_2by9w9_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_1kppo7g_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam d1h3s0zq atm_mj_1wugsn5 dir dir-ltr&quot;]</value>
      <webElementGuid>4c32855d-d4af-47cb-add8-a4ec63cf78d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[53]</value>
      <webElementGuid>676ca700-5310-4390-9e96-cad4d2d35b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel--tabs--0']/div/div/div[4]/div/div/div[2]/button[8]</value>
      <webElementGuid>678bb4a7-606b-4edc-b84d-afbcbe164243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::button[43]</value>
      <webElementGuid>3b2f4d66-f696-42b9-bd07-dbccd8129e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::button[43]</value>
      <webElementGuid>007a7c65-2bbf-47d0-bfe0-123a9789fdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact dates'])[1]/preceding::button[35]</value>
      <webElementGuid>7126e009-32ef-4b78-aecc-f448a876bd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='±1 day'])[1]/preceding::button[35]</value>
      <webElementGuid>bcbcc2f4-e631-4b4f-98a1-7cb5595b99bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[8]</value>
      <webElementGuid>5bd3db74-168b-4f45-906e-3e56c99ba724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '2' or . = '2')]</value>
      <webElementGuid>e379e546-9b9e-43e0-adc9-bfa1e506bf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
